@startuml
actor "Пользователь" as user
participant Bank
participant TgBot
participant API
participant BankService
participant Cache
participant Observability
participant App
participant MQ
participant DB
box Stats
    participant ExcelService
    participant S3
    participant LLM
box end


== Non stats sequence ==

user -> TgBot: Создать группу
activate TgBot
user -> TgBot: Добавить юза
user -> TgBot: Перераспределить доли
user -> TgBot: Удалить юза
user -> TgBot: Добавить трату
user -> TgBot: Отредачить группу
user -> TgBot: Распределить pending траты
user -> TgBot: Удалить сегодняшнюю трату

group Основной паттерн
TgBot -> API: Апдейт от тг
activate API
API -> Cache: Стейт диалога
activate Cache
Cache -->> API: Текущий стейт диалога
deactivate Cache
API -> App: Запрос в приложение
activate App
App -> DB: Запись в бд
activate DB
DB -> DB: Сохранение
DB -->> App
deactivate DB
App -->> API: Формирование ответа
App ->> Observability: Лог
deactivate App
API -->> TgBot: Бот отправь соо
deactivate API
end
TgBot -->> user: Ответ от бота
deactivate TgBot

newpage Bank Registry
user -> TgBot: Привязываю банк
activate user
activate TgBot
TgBot -> API: Запрос на привязку
activate API
API -->> TgBot: Ответ с ссылкой
deactivate API
TgBot -->> user: Перенаправление на сайт с OAuth
deactivate TgBot

user -> BankService: Привязываю банк
activate BankService

BankService -> Bank: Аутентификация юза
activate Bank
Bank -->> BankService: Access + Refresh Token
deactivate Bank
deactivate API

BankService -> DB: Запись Refresh в бд
activate DB
DB -> DB: Сохранение
DB -->> BankService: Айди/токен записан
deactivate DB
BankService ->> Observability: Лог
BankService --> TgBot: Успешная привязка к банку
deactivate BankService
activate TgBot
TgBot -->> user: Вы успешно привязали банк
deactivate TgBot
deactivate user

newpage Bank Update
user -> TgBot: Ручная синхронизация трат
activate TgBot
TgBot -> BankService: Запрос на ручную синхронизацию трат
deactivate TgBot
activate BankService

BankService -> Bank: Синхронизируй траты (раз в n часов/по запросу)
activate Bank
Bank -->> BankService: Вот новые траты
deactivate Bank

group Основной паттерн
BankService -> DB: Запись в бд
activate DB
DB -> DB: Сохранение
DB -->> BankService: Траты записаны
deactivate DB
BankService ->> Observability: Лог
BankService ->> MQ: "Новые траты, статус Pending"
deactivate BankService
activate MQ

API ->> MQ: Проверка наличия новых трат
activate API
MQ -->> API: Вот новые траты
deactivate MQ

API -> TgBot: Сообщение о наличии новых трат
deactivate API
activate TgBot
TgBot -> user: новые траты, распредели
deactivate TgBot
end

newpage Stats sequence

user -> TgBot: Дай график
activate TgBot
user -> TgBot: Дай диаграму

group Основной паттерн
TgBot -> API: Апдейт от тг
activate API

API -> Cache: Стейт диалога
activate Cache
Cache -->> API: Текущий стейт диалога
deactivate Cache
API -> App: Запрос в приложение
activate App
App -> Cache: Запрос на статистику в кэш
activate Cache
Cache -->> App: Ответ если актуальна
deactivate Cache
App ->> MQ: Запрос на статистику
activate MQ
MQ -> ExcelService: Запрос на формирование статистики
activate ExcelService
ExcelService -> DB: Чтение бд
activate DB
DB -->> ExcelService: Данные по юзу/группе
deactivate DB
ExcelService ->> S3: Документ Excel
activate S3

S3 -> S3: Сохранение
ExcelService ->> MQ: Статистика готова
deactivate ExcelService
MQ ->> App: Статистика лежит в S3
deactivate MQ
App -> S3: Запрос на скачивание статистики
S3 -->> App
deactivate S3
App -->> API: Формирование ответа
App ->> Observability: Лог
deactivate App
API -->> TgBot: Бот отправь соо
deactivate API
end
TgBot -->> user: Ответ от бота
deactivate TgBot

newpage LLM

user -> TgBot: Дай анализ
activate TgBot

TgBot -> API: Апдейт от тг
activate API
API -> Cache: Стейт диалога
activate Cache
Cache -->> API: Текущий стейт диалога
deactivate Cache

API ->> MQ: Запрос на анализ
activate MQ
LLM -> MQ: Запрос на формирование анализа
activate LLM
MQ -->> LLM
LLM -> DB: Чтение бд
activate DB
DB -->> LLM: Данные по юзу/группе
deactivate DB
LLM -> Cache: Текст анализа
activate Cache
LLM ->> MQ: Анализ готов
deactivate LLM
API ->> MQ: Спрос на готовность
MQ -->> API: Ответ готов
deactivate MQ
API -> Cache: Запрос на текст ответа
Cache -->> API
deactivate Cache
LLM ->> Observability: Лог
deactivate App
API -->> TgBot: Бот отправь соо
deactivate API
TgBot -->> user: Ответ от бота
deactivate TgBot
@enduml